# ---------- CONFIGURACIÓN DE CLIENTE ----------
YT_CLIENT_CONFIG = 'browser.json'

# ---------- RUTAS ----------
IMAGE_FOLDER = '/tmp'
SVG_FILENAME = "image.svg"

# ---------- DIMENSIONES SVG ----------
SVG_WIDTH = 500
SVG_HEIGHT = 350

# ---------- TARJETA ----------
CARD_MARGIN = 20
CARD_CORNER_RADIUS = 20
CARD_FILL_COLOR = "rgb(255,255,255)"
CARD_FILL_OPACITY = 0.08

# ---------- IMAGEN ----------
IMG_SIZE = 120
IMG_CORNER_RADIUS = 15
IMG_SHADOW_OFFSET = 5
IMG_SHADOW_OPACITY = 0.3
IMG_Y_POSITION = 80
IMG_THRESHOLD = 40

# ---------- FONDO DEGRADADO ----------
BG_GRADIENT_ID = "bgGradient"
BG_GRADIENT_START_COLOR = "#141E30"
BG_GRADIENT_END_COLOR = "#243B55"
GRADIENT_ANIMATION_DURATION = "10s"

# ---------- ANIMACIÓN IMAGEN ----------
IMAGE_PULSE_FROM = "1"
IMAGE_PULSE_TO = "1.05"
IMAGE_PULSE_DURATION = "3s"

# ---------- TEXTO TÍTULO ----------
TITLE_FONT_SIZE = "22px"
TITLE_FONT_WEIGHT = "bold"
TITLE_FONT_COLOR = "white"
TITLE_FONT_FAMILY = "sans-serif"
TITLE_MAX_CHARS = 20
TITLE_MAX_LINES = 2
TITLE_LINE_SPACING = 26

# ---------- TEXTO ARTISTA ----------
ARTIST_FONT_SIZE = "16px"
ARTIST_FONT_COLOR = "#CCCCCC"
ARTIST_FONT_FAMILY = "sans-serif"
ARTIST_Y_OFFSET = 10
